# Generated by Django 5.1.5 on 2025-09-11 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('s_autor', models.CharField(max_length=100)),
                ('nasc', models.DateField(blank=True, null=True)),
                ('nacio', models.CharField(blank=True, max_length=50, null=True)),
                ('biogr', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editora', models.CharField(max_length=100)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('subtitulo', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('idioma', models.CharField(default='Português', max_length=255)),
                ('ano', models.IntegerField()),
                ('paginas', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.IntegerField()),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponivel', models.BooleanField(default=True)),
                ('dimensoes', models.CharField(max_length=255)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.autor')),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.editora')),
            ],
        ),
    ]
