# Generated by Django 5.2.5 on 2025-08-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('s_nome', models.CharField(max_length=100)),
                ('nasc', models.DateField(blank=True, null=True)),
                ('nacio', models.CharField(blank=True, max_length=50, null=True)),
                ('biogr', models.TextField()),
            ],
        ),
    ]
