# Generated by Django 5.2.5 on 2025-08-21 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_livro_ano'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='name',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='s_name',
            new_name='s_autor',
        ),
        migrations.RenameField(
            model_name='editora',
            old_name='nome',
            new_name='editora',
        ),
    ]
