export interface Livro {
    id: number,
    titulo: string,
    subtitulo?: string | null,
    autor?: string | null,
    editora?: string | null,
    isbn?: string | null,
    descricao?: string | null,
    idioma?: string | null,
    ano: number,
    paginas: number,
    preco: number,
    estoque: number,
    desconto:number,
    disponivel: boolean,
    dimensoes?: string | null,
    peso: number,
}
